### ISSUE TITLE
lat e long nell'url della mappa

### ISSUE THREAD

**Issue by cirospat** [slarosa/rifiutocivico_repo#1]
se voglio avere l'url della mappa http://lrssvt.ns0.it/rifiutocivico/ zoommato ad es su Palermo, sarebbe utile avere un url che contiene i dati di lat e long. 
Così per es.: 
http://umap.openstreetmap.fr/it/map/spazi-verdi-fruibili-a-palermo-italia_14577#12/38.1360/13.4044

sarebbe possibile?

**Comment by slarosa** [comment]
@cirospat, riprova please. thanks!
(http://lrssvt.ns0.it/rifiutocivico/#11/38.1321/13.5087)

**Comment by pigreco** [comment]
@slarosa  @cirospat funziona
![image](https://user-images.githubusercontent.com/7631137/31309349-4200a1de-ab85-11e7-8f2e-0191dded5330.png)

**Comment by cirospat** [comment]
funziona grazie
